repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.7 # Replace with the latest Ruff version
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix] # Optional: automatically fix issues and fail if fixes are applied
    - id: ruff-format # Optional: add if you want to use Ruff's formatter
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      args: [--fail-under=90, --ignore-init-file, --ignore-private, --ignore-magic-methods]
      pass_filenames: false
