site_name: Mass2
nav:
  - Home: index.md
  - Docstrings: docstrings.md
  - Optimal filtering: filtering.md
  - Fluorescence lines: fluorescence.md
  - HCI lines: hci_lines_from_asd.md
  - LJH file format: LJHfiles.md
  - Testing: tests.md
  - About: about.md

theme: readthedocs

plugins:
- search
- mkdocstrings
