import marimo

__generated_with = "0.20.1"
app = marimo.App(width="medium", app_title="mass2 f3db sweep example")


@app.cell
def _(mo):
    mo.md("""
    # MASS2: Filter Sweep Example

    This notebook demonstrates how to load data, apply standard analysis steps, sweep multiple `f_3db` values for the 5-lag optimal filter, and extract a summary dataframe describing the filters applied to the data.
    """)
    return


@app.cell
def _():
    import numpy as np
    import polars as pl
    import pylab as plt
    import marimo as mo
    import mass2
    import pulsedata

    return mass2, mo, pl, plt, pulsedata


@app.cell
def _(mo):
    mo.md("""
    ## 1. Open the Data

    We load the `mnkalpha` `ljh` data via the `pulsedata` reference.
    """)
    return


@app.cell
def _(mass2, pulsedata):
    _p = pulsedata.pulse_noise_ljh_pairs["20230626"]

    # Create Channels object from the selected ljh folder
    data = mass2.Channels.from_ljh_folder(
        pulse_folder=_p.pulse_folder, 
        noise_folder=_p.noise_folder
    )
    data
    return (data,)


@app.cell
def _(mo):
    mo.md("""
    ## 2 & 3. Standard Analysis and f3db Sweeps

    For each channel, we:
    1. Summarize pulses and exclude bad pulses based on `pretrig_rms` and `postpeak_deriv` (`good_expr`).
    2. Sweep a list of 3dB cut-off frequencies (5, 10, 15, 20, 25 kHz).
    3. Make a 5-lag filter for each and follow up with a drift correction.
    """)
    return


@app.cell
def _(data, mass2):
    freqs_khz = [5, 10, 15, 20, 25]

    def _analyze_and_sweep(ch: mass2.Channel) -> mass2.Channel:
        # Standard analysis steps
        ch = (
            ch.summarize_pulses()
            .with_good_expr_pretrig_rms_and_postpeak_deriv()
            .driftcorrect(uncorrected_col="peak_value")
        )

        # Filter with multiple different f3db values
        for f in freqs_khz:
            f_3db = f * 1000.0
            y_col = f"5lagy_{f}khz"
            x_col = f"5lagx_{f}khz"

            # Apply optimal filter
            ch = ch.filter5lag(
                pulse_col="pulse",
                peak_y_col=y_col,
                peak_x_col=x_col,
                f_3db=f_3db,
            )
        return ch

    data2 = data.map(_analyze_and_sweep)
    return (data2,)


@app.cell
def _(mo):
    mo.md("""
    ## 4. Extract Filter Choices Dataframe

    Here we define a function that operates on a channel, inspects its steps to find the Optimal Filter Steps, and extracts the choices used to construct the filter (like `f_3db`) alongside the output column names and the predicted energy resolution metric (`predicted_v_dv`).

    Then, we apply this function to all channels and concatenate the outputs into a dataframe `df_filters`.
    """)
    return


@app.cell
def _(data2, mass2, pl):
    import dataclasses

    def extract_filter_history(ch: mass2.Channel) -> pl.DataFrame:
        records = []

        # Inspect all the steps that ran on the channel
        for step in ch.steps:
            if isinstance(step, mass2.core.filter_steps.OptimalFilterStep):
                # We found an OptimalFilterStep!
                filter_obj = step.filter

                # Extract choices and metrics from the filter dynamically
                filter_scalars = {}
                for field in dataclasses.fields(filter_obj):
                    val = getattr(filter_obj, field.name)
                    # Include standard scalar types, ignore arrays like 'values'
                    if isinstance(val, (int, float, str, bool)) or val is None:
                        filter_scalars[field.name] = val

                # Retrieve the column names generated by this step
                peak_x_col = step.output[0]
                peak_y_col = step.output[1]

                record = {
                    "ch_num": ch.ch_num,
                    "output_y_col": peak_y_col,
                    "output_x_col": peak_x_col,
                }
                record.update(filter_scalars)
                records.append(record)

        # If no optimal filter steps found, return empty df
        if not records:
            return pl.DataFrame()

        return pl.DataFrame(records)

    def collect_all_filter_histories(channels: mass2.Channels) -> pl.DataFrame:
        df_list = []
        for ch_num, ch in channels.channels.items():
            df_list.append(extract_filter_history(ch))

        if len(df_list) == 0:
            return pl.DataFrame()

        df_filters = pl.concat(df_list)
        import polars.selectors as cs
        # Drop columns that are entirely null
        return df_filters.drop(cs.by_dtype(pl.Null))

    df_filters = collect_all_filter_histories(data2)
    return (df_filters,)


@app.cell
def _(df_filters):
    df_filters
    return


@app.cell
def _(df_filters, mass2, pl, plt):
    plt.figure(figsize=(8, 5))

    # Get all unique channels and sort them
    channels = df_filters["ch_num"].unique().sort()

    for ch_num in channels:
        # Filter down to the single channel and sort by f_3db to ensure lines draw consecutively
        df_ch = df_filters.filter(pl.col("ch_num") == ch_num).sort("f_3db")
    
        # Plot f_3db against the automatically extracted predicted_v_over_dv field
        plt.plot(
            df_ch["f_3db"].to_numpy(), 
            df_ch["predicted_v_over_dv"].to_numpy(), 
            marker='o', 
            label=f"Ch {ch_num}"
        )
    
    plt.xlabel("f_3db (Hz)")
    plt.ylabel("predicted_v_over_dv (eV)")
    plt.title("Predicted Energy Resolution vs Filter Cutoff")

    # Only display legend if there are 15 or fewer channels so things don't get too messy
    if len(channels) <= 15:
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    
    plt.grid(True)
    plt.tight_layout()

    mass2.show()
    return


if __name__ == "__main__":
    app.run()
